// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/19/2025, 5:01:16 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/plugins/**/*.{js,ts,mjs}","/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/composables/**/*.{js,ts,mjs}","/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/utils/**/*.{js,ts,mjs}","/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/linjianhai/mycode/Udemy_copy_index/udemy-clone/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;